//! IPC commands for explicit device pairing.
//!
//! Pairing bootstraps cross-device sync: one device generates a code
//! (carrying its dial info + a fresh shared key), the other accepts it.
//! The acceptor immediately runs one sync exchange, which also
//! completes the pair on the initiator side (see
//! [`crate::p2p::device_sync`]).

use tauri::State;

use crate::crypto::pairing::{self, PairingCode};
use crate::domain::sync::SyncResult;
use crate::p2p::device_sync::{PairingHandshake, SyncRequest, SyncResponse};
use crate::p2p::sync;
use crate::AppState;

/// How long a generated pairing code stays valid (seconds).
const PAIRING_TTL_SECS: i64 = 600;

/// Shared handle to the per-profile database.
pub(crate) type DbHandle = std::sync::Arc<std::sync::Mutex<Option<crate::db::Database>>>;
/// Shared handle to the running P2P node.
pub(crate) type NodeHandle =
    std::sync::Arc<tokio::sync::Mutex<Option<crate::p2p::network::P2pNode>>>;

/// Generate a one-time pairing code for another device to accept.
///
/// Requires the P2P node to be running (the code embeds this device's
/// PeerId + dial addresses). The code is a secret — anyone holding it
/// can pair, so it expires after [`PAIRING_TTL_SECS`].
#[tauri::command]
pub async fn pairing_generate_code(state: State<'_, AppState>) -> Result<String, String> {
    // Live dial info from the running node.
    let status = {
        let node = state.p2p_node.lock().await;
        let node = node.as_ref().ok_or("start the P2P node before pairing")?;
        node.status().await.map_err(|e| e.to_string())?
    };
    let peer_id = status
        .peer_id
        .ok_or("P2P node has no PeerId yet — try again in a moment")?;
    // Prefer relay addresses (reachable through NAT); fall back to the
    // raw listen addresses. Drop loopback — a peer can't dial those.
    let mut addresses: Vec<String> = status
        .relay_addresses
        .into_iter()
        .chain(status.listening_addresses)
        .filter(|a| !a.contains("/127.0.0.1/") && !a.contains("/::1/"))
        .collect();
    addresses.dedup();

    let shared_key = pairing::generate_shared_key();

    let (stake_address, device_id, device_name) = {
        let db_guard = state.db.lock().map_err(|_| "db lock poisoned")?;
        let db = db_guard.as_ref().ok_or("database not initialized")?;
        let conn = db.conn();
        let stake = sync::local_stake_address(conn)?
            .ok_or("no local identity — finish onboarding first")?;
        let device_id = sync::get_or_create_local_device(conn, std::env::consts::OS)?;
        let name: Option<String> = conn
            .query_row(
                "SELECT device_name FROM devices WHERE is_local = 1",
                [],
                |r| r.get(0),
            )
            .ok();
        (stake, device_id, name)
    };

    let code = PairingCode {
        peer_id,
        addresses,
        shared_key,
        stake_address,
        device_id,
        device_name,
        platform: std::env::consts::OS.to_string(),
    };
    let code_str = pairing::encode(&code)?;

    {
        let db_guard = state.db.lock().map_err(|_| "db lock poisoned")?;
        let db = db_guard.as_ref().ok_or("database not initialized")?;
        sync::record_pending_pairing(
            db.conn(),
            &pairing::code_hash(&code_str),
            &shared_key,
            PAIRING_TTL_SECS,
        )?;
    }

    Ok(code_str)
}

/// Accept a pairing code generated by another of the user's devices.
///
/// Verifies the code belongs to the same user, records the pair, dials
/// the initiator, and runs one sync exchange (which completes the pair
/// on the other side). Returns the resulting [`SyncResult`].
#[tauri::command]
pub async fn pairing_accept_code(
    state: State<'_, AppState>,
    code: String,
) -> Result<SyncResult, String> {
    let started = std::time::Instant::now();
    let code_hash = pairing::code_hash(&code);
    let parsed = pairing::decode(&code)?;

    // Local identity context + same-user guard + record the pair.
    let (local_device_id, local_name) = {
        let db_guard = state.db.lock().map_err(|_| "db lock poisoned")?;
        let db = db_guard.as_ref().ok_or("database not initialized")?;
        let conn = db.conn();
        let local_stake = sync::local_stake_address(conn)?
            .ok_or("no local identity — finish onboarding first")?;
        if local_stake != parsed.stake_address {
            return Err("this pairing code belongs to a different account".to_string());
        }
        sync::complete_pairing(conn, &parsed)?;
        let device_id = sync::get_or_create_local_device(conn, std::env::consts::OS)?;
        let name: Option<String> = conn
            .query_row(
                "SELECT device_name FROM devices WHERE is_local = 1",
                [],
                |r| r.get(0),
            )
            .ok();
        (device_id, name)
    };

    // Seal our current state under the shared key.
    let sealed = {
        let db_guard = state.db.lock().map_err(|_| "db lock poisoned")?;
        let db = db_guard.as_ref().ok_or("database not initialized")?;
        let payload = sync::build_sync_payload(db.conn())?;
        sync::seal_payload(&parsed.shared_key, &payload)?
    };

    let peer: libp2p::PeerId = parsed
        .peer_id
        .parse()
        .map_err(|e| format!("bad peer id in code: {e}"))?;
    let addrs: Vec<libp2p::Multiaddr> = parsed
        .addresses
        .iter()
        .filter_map(|a| a.parse().ok())
        .collect();

    let request = SyncRequest {
        device_id: local_device_id,
        stake_address: parsed.stake_address.clone(),
        sealed,
        pairing: Some(PairingHandshake {
            code_hash,
            device_name: local_name,
            platform: std::env::consts::OS.to_string(),
        }),
    };

    let response = {
        let node = state.p2p_node.lock().await;
        let node = node.as_ref().ok_or("start the P2P node before pairing")?;
        // Best-effort dial; the request itself also triggers dialing.
        let _ = node.connect_peer(peer, addrs).await;
        node.sync_with_peer(peer, request)
            .await
            .map_err(|e| format!("sync with paired device failed: {e}"))?
    };

    finish_exchange(
        &state.db,
        &parsed.peer_id,
        &parsed.shared_key,
        response,
        started,
    )
}

/// Apply a peer's [`SyncResponse`] to the local DB and assemble a
/// [`SyncResult`]. Shared by pairing and the routine sync driver.
pub(crate) fn finish_exchange(
    db: &DbHandle,
    peer_id: &str,
    key: &[u8; 32],
    response: SyncResponse,
    started: std::time::Instant,
) -> Result<SyncResult, String> {
    let db_guard = db.lock().map_err(|_| "db lock poisoned")?;
    let db = db_guard.as_ref().ok_or("database not initialized")?;
    let conn = db.conn();

    match response {
        SyncResponse::Ok { sealed, merged } => {
            let payload = sync::open_payload(key, &sealed)?;
            let received = sync::payload_row_count(&payload);
            let (rows, settings) = sync::apply_sync_payload(conn, &payload)?;
            let locally_merged = rows + settings;
            let _ = sync::record_sync_event(conn, peer_id, "bidirectional", locally_merged);
            Ok(SyncResult {
                rows_sent: merged,
                rows_received: received,
                rows_merged: locally_merged,
                table_stats: vec![],
                duration_ms: started.elapsed().as_millis() as i64,
            })
        }
        SyncResponse::Unauthorized => {
            Err("peer rejected sync — not a paired device of this account".to_string())
        }
        SyncResponse::Error(e) => Err(format!("peer sync error: {e}")),
    }
}
