#!/usr/bin/env node
// Emit a `MessageKey` string-union type from the English catalog — the single
// source of truth for message keys. Run after editing en/*.json:
//
//   node scripts/i18n/gen-keys.mjs
//
// Produces src/i18n/keys.d.ts, consumed by the typed `t()` helper so key typos
// are compile errors under vue-tsc strict mode.

import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { resolve, dirname, basename } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const enDir = resolve(here, '../../src/locales/en')
const out = resolve(here, '../../src/i18n/keys.d.ts')

function leafKeys(obj, prefix, acc) {
  for (const [k, v] of Object.entries(obj)) {
    const path = prefix ? `${prefix}.${k}` : k
    if (v && typeof v === 'object' && !Array.isArray(v)) leafKeys(v, path, acc)
    else acc.push(path)
  }
}

const keys = []
for (const file of readdirSync(enDir)) {
  if (!file.endsWith('.json')) continue
  const ns = basename(file, '.json')
  const json = JSON.parse(readFileSync(resolve(enDir, file), 'utf8'))
  leafKeys(json, ns, keys)
}
keys.sort()

const union = keys.length ? keys.map((k) => `  | '${k}'`).join('\n') : '  never'
const body = `// AUTO-GENERATED by scripts/i18n/gen-keys.mjs — do not edit by hand.
// Regenerate after changing any src/locales/en/*.json.

export type MessageKey =
${union}
`
writeFileSync(out, body)
console.log(`gen-keys: wrote ${keys.length} keys → ${out}`)
