//! Group key management for classroom end-to-end encryption.
//!
//! Each classroom has a symmetric group key (AES-256-GCM) that encrypts
//! messages. The key is generated by the classroom owner and distributed
//! to members via X25519 ECDH key exchange.

use aes_gcm::aead::Aead;
use aes_gcm::{Aes256Gcm, KeyInit, Nonce};
use rand::rngs::OsRng;
use rand::RngCore;
use sha2::{Digest, Sha256};
use thiserror::Error;
use x25519_dalek::{PublicKey, StaticSecret};

/// Nonce size for AES-256-GCM (96 bits).
const NONCE_SIZE: usize = 12;

#[derive(Error, Debug)]
pub enum GroupKeyError {
    #[error("encryption failed: {0}")]
    EncryptionFailed(String),

    #[error("decryption failed: {0}")]
    DecryptionFailed(String),

    #[error("invalid data: {0}")]
    InvalidData(String),
}

/// Generate a random 32-byte group key.
pub fn generate_group_key() -> [u8; 32] {
    let mut key = [0u8; 32];
    OsRng.fill_bytes(&mut key);
    key
}

/// Encrypt a message with the group key (AES-256-GCM).
///
/// Returns `nonce(12) || ciphertext`.
pub fn encrypt_message(key: &[u8; 32], plaintext: &[u8]) -> Result<Vec<u8>, GroupKeyError> {
    let cipher = Aes256Gcm::new_from_slice(key)
        .map_err(|e| GroupKeyError::EncryptionFailed(e.to_string()))?;

    let mut nonce_bytes = [0u8; NONCE_SIZE];
    OsRng.fill_bytes(&mut nonce_bytes);
    let nonce = Nonce::from_slice(&nonce_bytes);

    let ciphertext = cipher
        .encrypt(nonce, plaintext)
        .map_err(|e| GroupKeyError::EncryptionFailed(e.to_string()))?;

    let mut result = Vec::with_capacity(NONCE_SIZE + ciphertext.len());
    result.extend_from_slice(&nonce_bytes);
    result.extend_from_slice(&ciphertext);
    Ok(result)
}

/// Decrypt a message encrypted with [`encrypt_message`].
///
/// Expects input formatted as `nonce(12) || ciphertext`.
pub fn decrypt_message(key: &[u8; 32], data: &[u8]) -> Result<Vec<u8>, GroupKeyError> {
    if data.len() < NONCE_SIZE {
        return Err(GroupKeyError::InvalidData(format!(
            "data too short: expected at least {} bytes, got {}",
            NONCE_SIZE,
            data.len()
        )));
    }

    let (nonce_bytes, ciphertext) = data.split_at(NONCE_SIZE);
    let nonce = Nonce::from_slice(nonce_bytes);

    let cipher = Aes256Gcm::new_from_slice(key)
        .map_err(|e| GroupKeyError::DecryptionFailed(e.to_string()))?;

    cipher
        .decrypt(nonce, ciphertext)
        .map_err(|e| GroupKeyError::DecryptionFailed(e.to_string()))
}

/// Derive an X25519 static secret from Ed25519 signing key scalar bytes.
///
/// Uses `SHA-256(signing_key_bytes)` as the X25519 secret. The result is
/// clamped internally by `x25519-dalek` when performing Diffie-Hellman.
pub fn derive_x25519_secret(ed25519_key_bytes: &[u8; 32]) -> StaticSecret {
    let hash = Sha256::digest(ed25519_key_bytes);
    let mut secret_bytes = [0u8; 32];
    secret_bytes.copy_from_slice(&hash);
    StaticSecret::from(secret_bytes)
}

/// Get the X25519 public key from a static secret.
pub fn x25519_public_key(secret: &StaticSecret) -> PublicKey {
    PublicKey::from(secret)
}

/// Derive an AES-256 key from an X25519 shared secret via SHA-256.
fn derive_aes_key(shared_secret: &x25519_dalek::SharedSecret) -> [u8; 32] {
    let hash = Sha256::digest(shared_secret.as_bytes());
    let mut aes_key = [0u8; 32];
    aes_key.copy_from_slice(&hash);
    aes_key
}

/// Encrypt a group key for a specific member using X25519 ECDH.
///
/// 1. `ECDH(our_secret, member_public)` produces a shared secret.
/// 2. `SHA-256(shared_secret)` derives an AES-256 key.
/// 3. `AES-256-GCM(aes_key, group_key)` encrypts the group key.
///
/// Returns: `nonce(12) || ciphertext(32 + 16)` (60 bytes total).
pub fn encrypt_key_for_member(
    group_key: &[u8; 32],
    member_x25519_pub: &PublicKey,
    our_x25519_secret: &StaticSecret,
) -> Result<Vec<u8>, GroupKeyError> {
    let shared_secret = our_x25519_secret.diffie_hellman(member_x25519_pub);
    let aes_key = derive_aes_key(&shared_secret);
    encrypt_message(&aes_key, group_key)
}

/// Decrypt a group key received from another member.
///
/// Reverses [`encrypt_key_for_member`] using our own X25519 secret and the
/// sender's X25519 public key.
pub fn decrypt_key_from_member(
    encrypted: &[u8],
    sender_x25519_pub: &PublicKey,
    our_x25519_secret: &StaticSecret,
) -> Result<[u8; 32], GroupKeyError> {
    let shared_secret = our_x25519_secret.diffie_hellman(sender_x25519_pub);
    let aes_key = derive_aes_key(&shared_secret);

    let decrypted = decrypt_message(&aes_key, encrypted)?;

    if decrypted.len() != 32 {
        return Err(GroupKeyError::InvalidData(format!(
            "expected 32-byte group key, got {} bytes",
            decrypted.len()
        )));
    }

    let mut key = [0u8; 32];
    key.copy_from_slice(&decrypted);
    Ok(key)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn encrypt_decrypt_message_roundtrip() {
        let key = generate_group_key();
        let plaintext = b"Hello, classroom!";

        let encrypted = encrypt_message(&key, plaintext).expect("encryption should succeed");
        let decrypted = decrypt_message(&key, &encrypted).expect("decryption should succeed");

        assert_eq!(decrypted, plaintext);
    }

    #[test]
    fn encrypt_decrypt_empty_message() {
        let key = generate_group_key();
        let plaintext = b"";

        let encrypted = encrypt_message(&key, plaintext).expect("encryption should succeed");
        let decrypted = decrypt_message(&key, &encrypted).expect("decryption should succeed");

        assert_eq!(decrypted, plaintext.to_vec());
    }

    #[test]
    fn wrong_key_fails_decryption() {
        let key1 = generate_group_key();
        let key2 = generate_group_key();
        let plaintext = b"secret message";

        let encrypted = encrypt_message(&key1, plaintext).expect("encryption should succeed");
        let result = decrypt_message(&key2, &encrypted);

        assert!(result.is_err(), "decryption with wrong key should fail");
    }

    #[test]
    fn different_messages_produce_different_ciphertext() {
        let key = generate_group_key();
        let plaintext = b"same message";

        let encrypted1 = encrypt_message(&key, plaintext).expect("encryption should succeed");
        let encrypted2 = encrypt_message(&key, plaintext).expect("encryption should succeed");

        // Random nonces ensure different ciphertext each time.
        assert_ne!(
            encrypted1, encrypted2,
            "same plaintext should produce different ciphertext due to random nonce"
        );
    }

    #[test]
    fn data_too_short_for_decryption() {
        let key = generate_group_key();
        let short_data = [0u8; 5];

        let result = decrypt_message(&key, &short_data);
        assert!(result.is_err(), "data shorter than nonce should fail");
    }

    #[test]
    fn key_exchange_roundtrip() {
        // Alice generates the group key and encrypts it for Bob.
        let group_key = generate_group_key();

        let alice_ed_bytes = [42u8; 32];
        let bob_ed_bytes = [99u8; 32];

        let alice_secret = derive_x25519_secret(&alice_ed_bytes);
        let bob_secret = derive_x25519_secret(&bob_ed_bytes);

        let alice_pub = x25519_public_key(&alice_secret);
        let bob_pub = x25519_public_key(&bob_secret);

        // Alice encrypts the group key for Bob.
        let encrypted = encrypt_key_for_member(&group_key, &bob_pub, &alice_secret)
            .expect("key encryption should succeed");

        // Expected size: 12 (nonce) + 32 (key) + 16 (GCM tag) = 60 bytes.
        assert_eq!(encrypted.len(), 60, "encrypted key should be 60 bytes");

        // Bob decrypts the group key using Alice's public key.
        let decrypted = decrypt_key_from_member(&encrypted, &alice_pub, &bob_secret)
            .expect("key decryption should succeed");

        assert_eq!(decrypted, group_key, "decrypted key should match original");
    }

    #[test]
    fn key_exchange_wrong_sender_fails() {
        let group_key = generate_group_key();

        let alice_secret = derive_x25519_secret(&[1u8; 32]);
        let bob_secret = derive_x25519_secret(&[2u8; 32]);
        let eve_secret = derive_x25519_secret(&[3u8; 32]);

        let bob_pub = x25519_public_key(&bob_secret);
        let eve_pub = x25519_public_key(&eve_secret);

        // Alice encrypts the group key for Bob.
        let encrypted = encrypt_key_for_member(&group_key, &bob_pub, &alice_secret)
            .expect("key encryption should succeed");

        // Bob tries to decrypt but uses Eve's public key as the sender
        // (wrong shared secret).
        let result = decrypt_key_from_member(&encrypted, &eve_pub, &bob_secret);
        assert!(
            result.is_err(),
            "decryption with wrong sender public key should fail"
        );
    }

    #[test]
    fn derive_x25519_is_deterministic() {
        let ed_bytes = [7u8; 32];
        let secret1 = derive_x25519_secret(&ed_bytes);
        let secret2 = derive_x25519_secret(&ed_bytes);

        let pub1 = x25519_public_key(&secret1);
        let pub2 = x25519_public_key(&secret2);

        assert_eq!(
            pub1.as_bytes(),
            pub2.as_bytes(),
            "same input should produce same X25519 keypair"
        );
    }
}
