name: Release (Mobile)

on:
  push:
    tags:
      - 'v*'
      - '[0-9]*'

jobs:
  publish:
    uses: ./.github/workflows/_mobile-build.yml
    with:
      tag: ${{ github.ref_name }}
      build_ref: ${{ github.ref }}
      publish_to_release: true
      include_android: true
      include_ios: ${{ vars.ENABLE_IOS_RELEASE == 'true' }}
      ios_export_method: app-store-connect
    secrets: inherit
