name: Release (Desktop)

on:
  push:
    tags:
      - 'v*'
      - '[0-9]*.[0-9]*.[0-9]*'

concurrency:
  group: release-desktop-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    uses: ./.github/workflows/_desktop-build.yml
    with:
      tag: ${{ github.ref_name }}
      build_ref: ${{ github.ref }}
      publish_to_release: true
      sign_updater: true
      include_linux: true
      include_windows: true
      include_macos: true
      include_linux_arm64: false
    secrets: inherit
